stages:
  data_ingestion:
    cmd: python3 src/liver/pipeline/stage_01_data_ingestion.py
    deps:
      - src/liver/pipeline/stage_01_data_ingestion.py
    outs:
      - artifacts/data_ingestion/liver.zip
      - artifacts/data_ingestion/liver.csv

  data_validation:
    cmd: python3 src/liver/pipeline/stage_02_data_validation.py
    deps:
      - src/liver/pipeline/stage_02_data_validation.py
      - artifacts/data_ingestion/liver.csv
    outs:
      - artifacts/data_validation/status.txt

  data_transformation:
    cmd: python3 src/liver/pipeline/stage_03_data_transformation.py
    deps:
      - src/liver/pipeline/stage_03_data_transformation.py
      - artifacts/data_ingestion/liver.csv
    outs:
      - artifacts/data_transformation/test.csv
      - artifacts/data_transformation/train.csv