stages:
  data_ingestion:
    cmd: python3 src/liver/pipeline/stage_01_data_ingestion.py
    deps:
      - src/liver/pipeline/stage_01_data_ingestion.py
    outs:
      - artifacts/data_ingestion/liver.zip
      - artifacts/data_ingestion/liver.csv