COLUMNS:
  Age: int64  
  Gender: object 
  Total_Bilirubin: float64
  Direct_Bilirubin: float64
  Alkaline_Phosphotase: int64  
  Alamine_Aminotransferase: int64  
  Aspartate_Aminotransferase: nt64  
  Total_Protiens: float64
  Albumin: float64
  Albumin_and_Globulin_Rati: float64
  Dataset: int64


TARGET:
  name: Dataset

mlflow:
  mlflow_uri: https://dagshub.com/fraidoon_omarzai/end-to-end-liver-project.mlflow
  experiment_name: Liver-> Random Forest
  run_name: MLOps